---
name: "Blog Static theme"
author: "Maxime Constantinian"
copyright: "Maxime Constantinian"
themeDir: "Blog"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "0.4.1"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes: []
    tags: []
    nodes: []
